### ISSUE TITLE
"_" should be excluded

### ISSUE THREAD

**Issue by sni** [nishanths/exhaustive#2]
It is quite common to skip entries in iota lists like this so you can explicitly distinguish an unset value:

```
const (
	_ SortDirection = iota
	Asc
	Desc
)
```

However, this throws a false positive:
```
missing cases in switch of type SortDirection: _ (exhaustive)
```

So i suggest removing the `_` when reading the enum.

**Comment by nishanths** [comment]
Agree `_` should be ignored, thanks. I can make the change.

**Comment by nishanths** [comment]
I'll submit a pull request to update the package in golangci-lint.

**Comment by sni** [comment]
great, thanks for the quick fix
