### ISSUE TITLE
missing diagnostics for switch statements that switch on a value whose type is a type parameter

### ISSUE THREAD

**Issue by nishanths** [nishanths/exhaustive#31]
It is unclear to me at this point what effect the upcoming go1.18 type parameter change will have on this analyzer. We may need to define the analyzer's behavior when type parameters are involved. The analzyer implementation may also need to be updated to handle type parameters.

**Comment by ghostsquad** [comment]
now that 1.18 is out, does anyone know if this still works?

**Comment by nishanths** [comment]
It continues to detect missing case clauses if the switch statement doesn't switch on a type-parameterized type.

However, if the switch statements switches on a type-parameterized type, exhaustive fails to detect missing cases. For example, for the switch statement in the function `foo` below, it should have reported missing `B`. In `bar`, it should have reported missing `B` and `C`. 

```go
package typeparam

type M int

const (
	A M = iota
	B
)

type N uint

const (
	C N = iota
	D
)

func foo[T M](v T) {
	switch v {
	case T(A):
	}
}

func bar[T M | N](v T) {
	switch v {
	case T(A):
	case T(D):
	}
}
```

One of the issues that should be addressed is that exhaustive doesn't check these switch statement because of this early-out return in `switch.go`:

https://github.com/nishanths/exhaustive/blob/c85349aae7e274d7dff96331a1f20481ba8ce157/switch.go#L94-L99

**Comment by nishanths** [comment]
Work-in-progress definition of the analyzer's behavior for type-parameterized types.

```
# Type parameters

A switch statement that switches on a value whose type is a type
parameter is checked for exhaustiveness iff each of term of the type
constraint is an enum type. The following switch statement will be
checked, assuming M, N, and O are enum types. To satisfy exhaustiveness,
all enum members for each of M, N, and O must be listed in the switch
statement's cases.

	func bar[T M | N | O](v T) {
		switch v {
		}
	}
```
