### ISSUE TITLE
Allow exhaustiveness checks on structs

### ISSUE THREAD

**Issue by FastNav** [nishanths/exhaustive#40]
Inspired from #35. There are certain structs whose fields you'd want to initialize exhaustively, i.e. whose fields should all be explicitly populated, even if with zero values. Being able to enforce that these structs are fully populated at build time seems like a natural extension of enum case exhaustiveness, with an arguably easier implementation in the most limited case.

# Example
Consider a struct representing the named arguments of a function such that all arguments are required except for the last.

```
//exhaustive:enforce
type DeleteUserArgs struct {
    UserID                        string
    DeletionTimestamp   time.Time
    RemoveFromGroups bool
    //exhaustive:ignore
    Reason                       string
}

func DeleteUser(ctx context.Context, args DeleteUserArgs) error {
// ...
}

func main() {
    args := &DeleteUserArgs {
        UserID:                       "FastNav",
        DeletionTimestamp:  time.Now().Add(-time.Hour),
        // forgot to specify whether user should be removed from groups :( -> exhaustive error
        // however, reason is optional
    }
    DeleteUser(context.Background(), args)
}
```

The above should result in a validation error at struct initialization because the `RemoveFromGroups` flag was not present. This is extremely useful for struct mapper functions when new fields are added.

## Enforcement Rules

Unlike implicit exhaustiveness enforcement for switch statements on enums, implicit exhaustiveness enforcement is probably unacceptable for struct initialization. It may even be a good idea to require `//exhaustive:enforce` directives at each point of struct initialization.

## Nice to Haves

Bonus points for being able to prove field initialization logic exists either inside or outside the struct literal.

```
    args := &DeleteUserArgs {
        UserID:                       "FastNav",
        DeletionTimestamp:  time.Now().Add(-time.Hour),
        // reason is optional
    }
    if userHasGroups() {
        args.RemoveFromGroups = true
        args.Reason = "Grouped user violated ToS"
    } else {
        args.RemoveFromGroups = false
    }
```

Proving definitively that all required fields are initialized is undecidable in general. The most viable approach is probably the one used by e.g. Java to prove that local variables are initialized.

**Comment by maratori** [comment]
Have you checked [exhaustruct](https://github.com/GaijinEntertainment/go-exhaustruct)?
Looks like it does what you need.

**Comment by nishanths** [comment]
Thank you for the issue. I think that exhaustiveness of struct fields may be better handled by other analyzers, such as [go-exhaustruct][1] (mentioned above) and [exhaustivestruct][2]. The scope of this package has been on exhaustiveness of enums, and I don't wish to add more scope. 

[1]: https://github.com/GaijinEntertainment/go-exhaustruct 
[2]: https://github.com/mbilski/exhaustivestruct
