### ISSUE TITLE
provide a way to exclude *_UNSPECIFIED generated for protobuf enums

### ISSUE THREAD

**Issue by powerman** [nishanths/exhaustive#8]
Protobuf guidelines recommends to define UNSPECIFIED at first value for all enums, to ensure 0 value (which is often received from peer which doesn't know about this enum at all) won't match any used enum value.

So, following guideline we have proto file like:
```proto
// Supported exchanges.
// New values may be added in the future.
enum Exchange {
    // Default value. This value is unused.
    EXCHANGE_UNSPECIFIED = 0;
    EXCHANGE_BITMEX = 1;
    EXCHANGE_BINANCE = 2;
}

```
As a result, we get something like this in auto-generated *.pb.go:
```go
// Supported exchanges.
// New values may be added in the future.
type Exchange int32

const (
	// Default value. This value is unused.
	Exchange_EXCHANGE_UNSPECIFIED Exchange = 0
	Exchange_EXCHANGE_BITMEX      Exchange = 1
	Exchange_EXCHANGE_BINANCE     Exchange = 2
)
```
Next, when parsing incoming message we have a switch like:
```go
	switch v {
	case api.Exchange_EXCHANGE_BITMEX:
		return dom.XBitmex, nil
	case api.Exchange_EXCHANGE_BINANCE:
		return dom.XBinance, nil
	default:
		return 0, fmt.Errorf("exchange: %w: %d", errUnknownEnum, v)
	}
```
And current implementation of your linter complains on this code:
```
missing cases in switch of type api.Exchange: Exchange_EXCHANGE_UNSPECIFIED
```

My point is:
- Adding extra case for UNSPECIFIED value is a bad idea because it must be handled exactly as any other unknown value, i.e. in same way as `default:` case. And there are no good way to add it: such case will either duplicate code from `default:` or contains `fallthrough` - in both ways it's too easy to occasionally make a mistake later (by changing code in only one of these two cases or by adding new case between `case UNSPECIFIED:` and `default:`).
- Enabling linter flag to make `default:` a catch-all will result in losing most of linter's power and many other mistakes won't be detected.

So, I propose to add one more flag (and related option in golangci-lint config) to define a regexp like `"_UNSPECIFIED$"` to ignore matched values.

**Comment by nishanths** [comment]
This is an excellent suggestion. I will be able to work on this after the next week.

**Comment by nishanths** [comment]
Support for this is now in master with the new `-ignore-pattern` flag. I'll tag a new version and make a pull request to update golangci-lint with the new ability.
